name: Build besthn
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "sources/sites/besthn/**"
      - "apps/besthn/**"

jobs:
  denoflow:
    runs-on: ubuntu-latest
    concurrency: build-besthn
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: DENO_DIR=./deno_dir deno run -A --unstable site/cli.ts besthn
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site/public
          force_orphan: false
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          external_repository: itsprivate/besthn
